JoesPizza/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JoesPizza.Helpers;
using JoesPizza.Models;
using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Authorization;

namespace JoesPizza.Controllers
{
    public class CartController : Controller
    {
        ApplicationDBContext _context;
        public CartController()
        {
            _context = new ApplicationDBContext();
        }
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            if (cart == null || cart.Count == 0)
            {
                ViewBag.cart = null;
                return View();
            }
            else
            {
                // var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
                return View();
            }
        }

       
        public IActionResult Additem(int id)
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else
            {
                if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
                {
                    List<CartItem> cart = new List<CartItem>();
                    cart.Add(new CartItem { Product = _context.Products.Find(id), Quantity = 1 });
                    SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
                }
                else
                {
                    List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                    int index = isExists(id);
                    if (index != -1)
                    {
                        cart[index].Quantity++;
                    }
                    else
                    {
                        cart.Add(new CartItem { Product = _context.Products.Find(id), Quantity = 1 });
                    }
                    SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
                }
                return RedirectToAction("Index");
            }

            
               
        }

        public int isExists(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
        public IActionResult Remove(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExists(id);
            cart.RemoveAt(index);
            SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");

        }

        //public IActionResult Pay()
        //{
        //    return View();
        //}
    }
}

JoesPizza/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using JoesPizza.Models;
using Stripe;

using System.Threading.Tasks;
using JoesPizza.Helpers;
using JoesPizza.Helpers;

namespace JoesPizza.Controllers
{
    public class PaymentController : Controller
    {
        public static string orderId { get; set; }
        public IActionResult OrderStatus()
        {
            
            return View("OrderStatus");
           

        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(string stripeToken)
        {
            try
            {
                StripeConfiguration.SetApiKey("pk_test_51Jc8eoSChZXLAWtZQhX2hNNqhGXUNQK0udYqXBMmpayUdIdAXMJEVU8IkMs6hiXYltW8DXzJrZcnIc3CsARwJUvA00CL3YY96H");
                StripeConfiguration.ApiKey = "sk_test_51Jc8eoSChZXLAWtZXTYzM1Qne9n5KcZohrTkn7tvzILZKpwVCc8nKYkEBg0xlL4FUREH63t41jK3usJTTbqmNnOO00Kb4aifNL";
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                var amountToPay = cart.Sum(item => item.Product.Price * item.Quantity);
                amountToPay=amountToPay*100;
                var myCharge = new ChargeCreateOptions();
                // always set these properties
               
                myCharge.Amount = ((long?)amountToPay);
                myCharge.Currency = "INR";
                myCharge.ReceiptEmail = "stripeEmail@gmail.com";
                myCharge.Description = "Sample Charge";
                myCharge.Source = stripeToken;
                myCharge.Capture = true;
                var chargeService = new ChargeService();
                Charge stripeCharge = chargeService.Create(myCharge);
             
                var model = new ChangeViewModel();
                model.ChargeId = stripeCharge.Id;
                return View("OrderStatus",model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

JoesPizza/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JoesPizza.Models;


namespace JoesPizza.Controllers
{
    public class ProductController : Controller
    {
        ApplicationDBContext context;
        public ProductController()
        {
            context = new ApplicationDBContext();
        }

        public IActionResult Index()
        {
            var products = context.Products.ToList();
            return View(products);
        }
        public IActionResult Details(int id)
        {
            var product = context.Products.Find(id);
            return View(product);

        }
    }
}

JoesPizza/Views/Cart/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    .truncated {
        display: -webkit-box;
        -webkit-line-clamp: 4;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>
@if (ViewBag.cart == null)
{
    <h5>Cart is empty</h5>
    <a class="btn btn-warning m-1" asp-controller="Product" asp-action="Index">Continue Shopping</a>

}


else
{
<div style="padding-right:130px;padding-left:130px">
    @foreach (var item in ViewBag.cart)
    {
        
        <div class="row p-2 bg-white border rounded" style="margin-bottom:10px">
            <div class="col-md-3 mt-1"><img src=@item.Product.Image width="290" height="150"></div>
            <div class="col-md-6 mt-1">
                <h5 name="PName">@item.Product.Name</h5>

                <p class="truncated">@item.Product.Description<br><br></p>
            </div>
            <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                <div class="d-flex flex-row align-items-center">
                    <h4 class="mr-1">₹ @item.Product.Price</h4><br />

                </div>
                <p>Quantity : @item.Quantity   Item Total: ₹<b>@(item.Product.Price * item.Quantity)</b></p>

                <h6 class="text-success">Free shipping</h6>
                <div class="d-flex flex-column mt-4"><a class="btn btn-outline-danger btn-sm" asp-controller="Cart" asp-action="Remove" asp-route-id="@item.Product.Id" type="button">Remove</a></div>
            </div>
        </div>

    }
    <br />
    <br />

    <form style="color:green;margin-left:83%" asp-controller="Payment" asp-action="Create" method="POST" id="payment-form">
       
        <b>TOTAL ₹@ViewBag.total </b><br />


        <script src="//checkout.stripe.com/v2/checkout.js"
                class="stripe-button"
                data-key="pk_test_51Jc8eoSChZXLAWtZQhX2hNNqhGXUNQK0udYqXBMmpayUdIdAXMJEVU8IkMs6hiXYltW8DXzJrZcnIc3CsARwJUvA00CL3YY96H"
                data-locale="auto"
                data-description="Sample Charge"
                data-amount=@(ViewBag.total * 100)>

        </script>
    </form>
    <a class="btn btn-warning m-1" asp-controller="Product" asp-action="Index">Continue Shopping</a>
    
</div>
}